
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-citacloud-rivtower-com-v1-account
  failurePolicy: Fail
  name: maccount.kb.io
  rules:
  - apiGroups:
    - citacloud.rivtower.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - accounts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-citacloud-rivtower-com-v1-chainconfig
  failurePolicy: Fail
  name: mchainconfig.kb.io
  rules:
  - apiGroups:
    - citacloud.rivtower.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - chainconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-citacloud-rivtower-com-v1-chainnode
  failurePolicy: Fail
  name: mchainnode.kb.io
  rules:
  - apiGroups:
    - citacloud.rivtower.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - chainnodes
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-citacloud-rivtower-com-v1-account
  failurePolicy: Fail
  name: vaccount.kb.io
  rules:
  - apiGroups:
    - citacloud.rivtower.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - accounts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-citacloud-rivtower-com-v1-chainconfig
  failurePolicy: Fail
  name: vchainconfig.kb.io
  rules:
  - apiGroups:
    - citacloud.rivtower.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - chainconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-citacloud-rivtower-com-v1-chainnode
  failurePolicy: Fail
  name: vchainnode.kb.io
  rules:
  - apiGroups:
    - citacloud.rivtower.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - chainnodes
  sideEffects: None
