
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: cita
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app: cita-cloud-operator
    app.kubernetes.io/instance: cita-cloud-operator
    app.kubernetes.io/name: cita-cloud-operator
