# permissions for end users to view chainnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chainnode-viewer-role
rules:
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - chainnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - chainnodes/status
  verbs:
  - get
