
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - chainconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - chainconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - chainconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - chainnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - chainnodes/finalizers
  verbs:
  - update
- apiGroups:
  - citacloud.rivtower.com
  resources:
  - chainnodes/status
  verbs:
  - get
  - patch
  - update
