apiVersion: citacloud.rivtower.com/v1
kind: ChainNode
metadata:
  name: my-node-1
  namespace: cita
spec:
  nodeInfo:
    cluster: k8s-1
    domain: www.hello.com
    port: 9630
  chain: my-chain
  kmsPassword: "123456"
  storageSize: 21474836480
  storageClassName: "nas-client-provisioner"
#  action: "Initialize"
  action: "Start"
  # 移除
  type: "Consensus"
  logLevel: info
  # 移动至链级
  imageInfo:
    pullPolicy: Always
