apiVersion: citacloud.rivtower.com/v1
kind: ChainNode
metadata:
  name: my-node-1
  namespace: cita
spec:
  nodeInfo:
    cluster: k8s-1
    account: node1-account
    externalIp: "1.1.1.1"
    port: 9630
  chainName: test-chain
  storageSize: 21474836480
  storageClassName: "nas-client-provisioner"
  action: "Initialize"
#  action: "Start"
  logLevel: info
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 4000m
      memory: 8192Mi
