apiVersion: citacloud.rivtower.com/v1
kind: ChainNode
metadata:
  name: my-node-3
  namespace: cita
spec:
  nodeInfo:
    cluster: k8s-1
    account: node3-account
    externalIp: "3.3.3.3"
    port: 9630
  chainName: test-chain
  storageSize: 21474836480
  storageClassName: "nas-client-provisioner"
  action: "Initialize"
#  action: "Start"
  logLevel: info
  resources: {}