apiVersion: citacloud.rivtower.com/v1
kind: ChainNode
metadata:
  name: my-node-1
  namespace: cita
spec:
  nodeInfo:
    cluster: k8s-1
    domain: www.hello.com
    internalIp: localhost
    port: 9630
  chainName: my-chainconfig
  kmsPassword: "123456"
  storageSize: 21474836480
  storageClassName: "nas-client-provisioner"
#  storageClassName: "local-path"
#  action: "Initialize"
  action: "Create"
  type: "Consensus"
  logLevel: info
  imageInfo:
    pullPolicy: Always