apiVersion: apps/v1
kind: Deployment
metadata:
  name: cita-cloud-operator
  namespace: {{.Release.Namespace}}
  labels:
    control-plane: cita-cloud-operator
spec:
  selector:
    matchLabels:
      control-plane: cita-cloud-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: cita-cloud-operator
      labels:
        control-plane: cita-cloud-operator
    spec:
#      securityContext:
#        runAsNonRoot: true
      containers:
        - command:
            - /cita-cloud-operator
          args:
            - --leader-elect
          image: {{ .Values.global.registry }}/{{ .Values.global.repository }}/cita-cloud-operator:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: operator
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: cita-cloud-operator
      terminationGracePeriodSeconds: 10
