{{- if .Values.enableWebhooks }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cita-cloud-operator-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - cita-cloud-operator-webhook-service.{{ .Release.Namespace }}.svc
    - cita-cloud-operator-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: cita-cloud-operator-selfsigned-issuer
  secretName: webhook-server-cert
{{- end }}