name: Integration Testing

on:
  pull_request:
  push:
    branches:
      - integration-testing

jobs:
  deploy-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: Testing
        run: |
          docker build -t local:sleep-test -f ./Dockerfile-test .
          kind load docker-image local:sleep-test --name chart-testing
          docker ps
          docker exec -it chart-testing-control-plane crictl images
