name: Integration Testing

on:
  pull_request:
  push:
    branches:
      - integration-testing

jobs:
  deploy-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          kubectl get sc
          helm repo add cita-cloud-operator https://cita-cloud.github.io/cita-cloud-operator
          kubectl create ns cita
          helm install cita-cloud-operator cita-cloud-operator/cita-cloud-operator -n=cita
          while [[ `kubectl get pod -ncita | grep cita-cloud-operator | awk '{print $3}'` != "Running" ]]
          do
            echo "cita-cloud-operator pod is not Running..."
            sleep 1
          done
          echo "cita-cloud-operator pod is Running!"